#! /usr/bin/bash

set -e

cmake-build-debug/dawn "`dirname "$1"`" "$1" dawntmp.o
STDLIB="
#include <stdio.h>

extern long readln() {
    long n;
    scanf(\"%ld\", &n);
    return n;
}

extern void writeln(long n) {
    printf(\"%ld\n\", n);
}"

echo "$STDLIB" | clang -o"$2" -std=c99 dawntmp.o -xc -

rm dawntmp.o
